// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8OTerB8v80xC5PAYI5aiALcL25PyOEg0',
    appId: '1:13980846794:web:c59f7cb4d4cccc94408233',
    messagingSenderId: '13980846794',
    projectId: 'zyra-project-5ed13',
    authDomain: 'zyra-project-5ed13.firebaseapp.com',
    storageBucket: 'zyra-project-5ed13.firebasestorage.app',
    measurementId: 'G-8X0P9WHGK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXwlZW2A-Vt6TMGE9kW-JMHW6OC5pm6cY',
    appId: '1:13980846794:android:edba1e492e14f572408233',
    messagingSenderId: '13980846794',
    projectId: 'zyra-project-5ed13',
    storageBucket: 'zyra-project-5ed13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrpjPcztc3xnMyUMviSBB-XzlXRWNgHYI',
    appId: '1:13980846794:ios:7ee2b9a6ace26034408233',
    messagingSenderId: '13980846794',
    projectId: 'zyra-project-5ed13',
    storageBucket: 'zyra-project-5ed13.firebasestorage.app',
    iosBundleId: 'com.example.zyra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrpjPcztc3xnMyUMviSBB-XzlXRWNgHYI',
    appId: '1:13980846794:ios:7ee2b9a6ace26034408233',
    messagingSenderId: '13980846794',
    projectId: 'zyra-project-5ed13',
    storageBucket: 'zyra-project-5ed13.firebasestorage.app',
    iosBundleId: 'com.example.zyra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8OTerB8v80xC5PAYI5aiALcL25PyOEg0',
    appId: '1:13980846794:web:f7d282ac73d1a526408233',
    messagingSenderId: '13980846794',
    projectId: 'zyra-project-5ed13',
    authDomain: 'zyra-project-5ed13.firebaseapp.com',
    storageBucket: 'zyra-project-5ed13.firebasestorage.app',
    measurementId: 'G-6X0LM8EXCZ',
  );
}
