name: zyra
description: "Zyra - Women Health App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0

  # STATE MANAGEMENT
  provider: ^6.0.6
  package_info_plus: ^10.1.0

  # LOCAL STORAGE
  shared_preferences: ^2.2.2
  sqflite: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.2

  # IMAGES
  image_picker: ^1.1.2

  # PERMISSIONS
  permission_handler: ^11.3.1

  # FIREBASE
  firebase_core: ^4.0.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.0.0

  # NOTIFICATIONS
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ✅ IMPORTANT FOR L10N
  generate: true

  assets:
    - assets/images/
    - assets/imagesBaby/
    - assets/nutrition.json
